version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_toy
    ports:
      - '5672:5672' # Porta do protocolo AMQP
      - '15672:15672' # Painel de Gerenciamento (Login: guest / guest)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data:
